name: wtie
channels:
    - defaults
    - conda-forge
    - pytorch
dependencies:
    - defaults::python=3.7.9
    - defaults::jupyter
    - defaults::ipython
    - defaults::multimethod
    - defaults::cudatoolkit=10.2
    - pytorch::pytorch=*=*cuda10.2*
    - defaults::tensorboard
    - defaults::numpy
    - defaults::pandas
    - defaults::matplotlib
    - defaults::scipy
    - defaults::scikit-image
    - defaults::scikit-learn
    - defaults::h5py
    - defaults::numba
    - defaults::pyyaml
    - defaults::pathlib
    - defaults::pytest
    - defaults::pdoc3
    - defaults::pylint
    - defaults::tqdm
    - conda-forge::noise
    - pytorch::torchvision
    - pip
    - pip:
          - segyio
          - lasio
          - ax-platform==0.1.20
          - dtaidistance
          - setuptools==59.5.0